In [1]:
################################################################################################################################
#                                                                                                                              #
#        practical-14                                                                                                          #
#        Our Problem  Defination is : Movie Recommended System  [ with the use of NLP (Countvectorized ,Cosine_Similarity) ]   #                                                                                                         
#                                                                                                                              #
#                                                                                                                              #
#    ''''Name: Arpita Makwana                                                                                                    # 
#        Enrollnment no: 216270307069'''' 
#  '''Name: Nirali Joshi'''
#       Enrollnment no: 216270307067'''                                                                                                                        #                                                                                                                      
#                                                                                                                              #
#                                                                                                                              #
#                                                                                                                              #
################################################################################################################################

In [1]:
#importing the necessay library.

import pandas as pd

In [2]:
#Read the CSV file.

movies=pd.read_csv('dataset.csv')

In [4]:
#show the first 10 column.

movies.head(10)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
5,667257,Impossible Things,"Family,Drama",es,"Matilde is a woman who, after the death of her...",14.358,2021-06-17,8.6,255
6,129,Spirited Away,"Animation,Family,Fantasy",ja,"A young girl, Chihiro, becomes trapped in a st...",92.056,2001-07-20,8.5,13093
7,730154,Your Eyes Tell,"Romance,Drama",ja,"A tragic accident lead to Kaori's blindness, b...",51.345,2020-10-23,8.5,339
8,372754,Dou kyu sei – Classmates,"Romance,Animation",ja,"Rihito Sajo, an honor student with a perfect s...",14.285,2016-02-20,8.5,239
9,372058,Your Name.,"Romance,Animation,Drama",ja,High schoolers Mitsuha and Taki are complete s...,158.270,2016-08-26,8.5,8895

In [3]:
#movies.describe() provides statistical summary information for the numerical columns in the "movies"

movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [4]:
#movies.info() is used to retrieve information about the DataFrame "movies" in Python


movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [5]:
#this is check the any value is null or not.

movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

Feature Selection Part

In [6]:
#show the columns.
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [7]:
#this is feature in movie recomended system  

movies=movies[['id', 'title', 'overview', 'genre']]

In [8]:
movies

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [9]:
#we can threee feature merge in single column [tags].

movies['tags'] = movies['overview']+movies['genre']

In [12]:
movies

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [10]:
#create a new data and removing the column overview and genre.

new_data  = movies.drop(columns=['overview', 'genre'])

In [11]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [14]:
#Start our main part:
#we can import the sklearn and train our model with the use of feature_extration and Countvectorizer.[Feature_extration
#is a part of the NLP].

from sklearn.feature_extraction.text import CountVectorizer

In [15]:
#limits the 10000 and stop count is used to removig some word like comman word 'a','an','in','the' .
cv=CountVectorizer(max_features=10000, stop_words='english')

In [16]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [17]:
# to transform the text data in the 'tags' column.

vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [18]:
#vector.shape provides the dimensions (number of rows and columns)of the numerical values.

vector.shape

(10000, 10000)

In [19]:
#import the cosine simiularity[it's also part of the Sklearn as well as Cosine_similarity]

from sklearn.metrics.pairwise import cosine_similarity

In [20]:
#find the similarity 

similarity=cosine_similarity(vector)

In [21]:
similarity

array([[1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
        0.06388766],
       [0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
        0.        ],
       [0.12888482, 0.07624929, 1.        , ..., 0.02273314, 0.06655583,
        0.08645856],
       ...,
       [0.07559289, 0.        , 0.02273314, ..., 1.        , 0.03253   ,
        0.02817181],
       [0.11065667, 0.03636965, 0.06655583, ..., 0.03253   , 1.        ,
        0.0412393 ],
       [0.06388766, 0.        , 0.08645856, ..., 0.02817181, 0.0412393 ,
        1.        ]])

In [22]:
#test the similarity.

new_data[new_data['title']=="The Godfather"].index[0]

2

In [23]:

#This code calculates the "distance" between a reference vector (index[2]) and all other vectors,
#sorts them in descending order by their values, and then prints the titles of the top 5 

distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [24]:
#find the index of movie dataset and match the input title.
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    # index= new_data.sample(frac=1).reset_index(drop=True)
    print(index)
    distance = sorted(list(enumerate(similarity[index+1])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [ ]:
recommand("Iron Man")

In [ ]:
#The line "import pickle" is used to import the Python module "pickle," which provides a way to serialize
#and deserialize Python objects.

import pickle

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

# Load the dataset
movies = pd.read_csv('dataset.csv')

# Select relevant columns
movies = movies[['id', 'title', 'overview', 'genre']]

# Combine 'overview' and 'genre' into 'tags'
movies['tags'] = movies['overview'] + movies['genre']

# Drop unnecessary columns
new_data = movies.drop(columns=['overview', 'genre'])

# Split the dataset into training and validation sets
train_data, validation_data = train_test_split(new_data, test_size=0.2, random_state=42)

# Vectorize the 'tags' column
cv = CountVectorizer(max_features=10000, stop_words='english')
vector = cv.fit_transform(train_data['tags'].values.astype('U')).toarray()

# Calculate cosine similarity
similarity = cosine_similarity(vector)

# Function to calculate precision at k
def precision_at_k(predictions, validation_set, k):
    precision_values = []
    for user_id, recommended_items in predictions.items():
        relevant_items = set(validation_set[validation_set['id'] == user_id]['title'])
        recommended_items = set(recommended_items[:k])
        precision = len(recommended_items.intersection(relevant_items)) / k
        precision_values.append(precision)
    return sum(precision_values) / len(precision_values)

# Function to recommend movies for a user
def recommend_movies_for_user(user_id):
    index = new_data[new_data['id'] == user_id].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector: vector[1])
    recommendations = [new_data.iloc[i[0]].title for i in distance[1:6]]
    return recommendations

# Generate recommendations for each user in the validation set
user_predictions = {
    user_id: recommend_movies_for_user(user_id) for user_id in validation_data['id']
}

# Calculate precision at k
k = 5  # You can adjust k based on the number of recommendations you want to evaluate
precision = precision_at_k(user_predictions, validation_data, k)
print(f'Precision at {k}: {precision}')

In [40]:
#serialize the new data into a binary file named 'movies_list.pk' and wb is write into file 
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [63]:
#This line of code uses the pickle.dump function to serialize and save the "similarity" data
#(likely a similarity matrix or some other data structure) into a binary file named 'similarity.pkl.' 

pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [64]:
#This line of code uses pickle.load to deserialize and load the binary data from the 'movies_list.pkl' 
#file, which likely contains a serialized DataFrame (such as "new_data").

pickle.load(open('movies_list.pkl', 'rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...